### ISSUE TITLE
Support for bioconda/singularity/nextflow

### ISSUE THREAD

**Issue by uel3** [czbiohub-sf/MIDAS#135]
Are there plans for a containerized version of MIDAS2 (singularity, bioconda)? Or plans for an nf-core module?

**Comment by zhaoc1** [comment]
Hi, 

We have conda for MIDAS2 (-c zhaoc1) and also Dockerfiles. I don't think we have plans for singularity, bioconda or nf-core module for MIDAS2. Thanks.

Chunyu
