### ISSUE TITLE
Pulling uhgg gtdb full databases

### ISSUE THREAD

**Issue by kkerns85** [czbiohub-sf/MIDAS#143]
Hi, very excited to see this major update coming from MIDAS! Running into issues accessing the full DBs for both the UHGG and GTDB. Are these accessible elsewhere for download using wget or curl? I keep running into issues with (see attached error log).

In addition, although reading that classification on the GTDB and UHGG cost about $80K!!!! are there any plans to provide updated versions in the near future? GTDB is currently on R220 and has significant amount of new genomes added to the collection. I also see in some code there is reference to UHGG-v2. 

Thanks for any help on this and very excited to use this updated tool!

[Midas3_DB_Error_log.txt](https://github.com/user-attachments/files/16553849/Midas3_DB_Error_log.txt)

**Comment by kkerns85** [comment]
I also confirmed that numpy is installed and in my path.

**Comment by kkerns85** [comment]
Got it to work! Thanks!

**Comment by zhaoc1** [comment]
That's great! Glad you figured it out!

MIDASDB v3 is actually based on GTDB r202 and UHGG v2, by `midas2 database --list`.
